Fix ANSI control sequences in Jupyter notebooks
pavdmyt/yaspin pull request #193
Opened 2022-05-04 15:56 UTC by nschrader

I suggest this fix for https://github.com/pavdmyt/yaspin/issues/176. 
1. it checks if stdout is a TTY before printing [private](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences) ANSI control sequences (DECTCEM 1&2)
2. I also corrected the EL sequence, which was missing the 0 for its canonical form (`^[K` is a special case of `^[0K`)
3. I added a CR before the EL (which was already partly the case, but cluttered around the code).
4. some clean-up in the code calling the foregoing functions

Other control sequences seem to work fine in Jupyter. Tests:
- Jupyter notebook
![Peek 2022-05-05 10-31](https://user-images.githubusercontent.com/17453878/166888103-8fcc7569-be64-4a4b-9033-0216144e5818.gif)
- Terminal
![Peek 2022-05-05 10-32](https://user-images.githubusercontent.com/17453878/166888170-35e0d59e-afd9-4235-adf8-c1c6b5829f67.gif)

2022-05-06 09:02 UTC, pavdmyt commented
Hi @nschrader 

Thanks for your PR!
I'd suggest to [squash your commits](https://stackoverflow.com/questions/35703556/what-does-it-mean-to-squash-commits-in-git) and write a meaningful commit message. Also, seems like Travis CI integration has failed in some way, so I have to enable automatic PR testing again.

2022-05-06 09:09 UTC, pavdmyt commented
Running tests manually (`make test`) on your branch, there are following failures:
```
    1236 passed
      13 failed
         - tests/test_in_out.py:92 test_hide_show['non-ascii str']
         - tests/test_in_out.py:78 test_write['non-ascii str']
         - tests/test_in_out.py:78 test_write['non-ascii unicode str']
         - tests/test_in_out.py:228 test_write_non_str_objects[foo-foo]
         - tests/test_in_out.py:228 test_write_non_str_objects[obj1-{'cat': 'meow'}]
         - tests/test_in_out.py:92 test_hide_show['non-ascii unicode str']
         - tests/test_in_out.py:228 test_write_non_str_objects[23-23]
         - tests/test_in_out.py:78 test_write['ascii str']
         - tests/test_in_out.py:228 test_write_non_str_objects[obj3-['foo', 'bar', "'", 23]]
         - tests/test_in_out.py:92 test_hide_show['empty']
         - tests/test_in_out.py:92 test_hide_show['ascii str']
         - tests/test_in_out.py:157 test_spinner_hiding_with_context_manager
         - tests/test_in_out.py:181 test_spinner_nested_hiding_with_context_manager
     714 skipped
```

You have to ensure test are working correctly and add a specific test cases for you fix.

2022-05-06 09:11 UTC, pavdmyt requested changes
Please address the above comments.

2022-05-06 17:36 UTC, nschrader commented
Thanks for your review, Pavel. Couldn't you simply "squash and merge" this PR on GitHub? So I don't need to force-push anything.

I didn't see the test suite, thanks for the hint! Should be all good now, just needed to adjust for new EL sequence.

2022-05-10 08:06 UTC, pavdmyt reviewed
Looks good :+1: 
Just a minor item to clarify.

2022-05-10 08:06 UTC, pavdmyt commented on yaspin/core.py
> +            sys.stdout.write("{0}{1}\n".format(_text, " " * fill))
I'm not sure I understand this part. Why this extra filling is needed?

2022-05-11 07:46 UTC, pavdmyt approved these changes
LGTM

2022-05-11 07:50 UTC, merged

2022-05-11 07:51 UTC, pavdmyt commented
@nschrader once again, thanks for your contribution!

I'll include this into the next yaspin release.

2022-05-11 18:48 UTC, nschrader commented
@pavdmyt sorry for the mess, but I was testing again this morning and noticed some more problems which Jupyter. Turns out that `^[K` isn't actually clearing the line, rather just printing 3 white spaces. That's why `^[0K` "fixed" some issues (well, just overrode one more character). I added some more commits, reverting the EL sequence and overriding the current line with white spaces, the only thing that reliably works in Jupyter.

I'd suggest that you revert this PR and I open a new one, so there is a clean trace.