feat: add parameter to for output stream
pavdmyt/yaspin pull request #235
Opened 2023-10-18 14:56 UTC by bpshaver

The addition of the `stream` parameter allows the user to choose to send the yaspin spinner output to a stream or TextIO object other than sys.stdout. The most obvious use for this feature is to set the stream to stderr to support piping of output like `python main.py > some.log` and seeing the yaspin spinner in the terminal while stdout goes to `some.log`

2023-10-18 14:57 UTC, bpshaver commented on yaspin/core.py
> -    @staticmethod
Because of calls so `isatty` these can no longer be static methods

2023-10-18 16:27 UTC, pavdmyt commented
@bpshaver please run `make fmt` on your changes so that `check-fmt` check can succeed in CI.

2023-10-18 16:50 UTC, bpshaver commented
> @bpshaver please run `make fmt` on your changes so that `check-fmt` check can succeed in CI.

Done.

Does this seem like a sensible change? If so, I'll look through the failing test cases now.

2023-10-18 18:00 UTC, bpshaver commented on tests/test_in_out.py
> +            sp.stop()
I don't know why `sp.stop()` was raising an exception due to an already closed file.

2023-10-22 17:25 UTC, pavdmyt commented
@bpshaver thanks for your contribution! I'll try to review this thoroughly next week.

2023-10-26 14:49 UTC, pavdmyt commented
Apparently it is possible to detect situations when different streams are not tty:
```
import os

if not os.isatty(sys.stdout.fileno()):
    print("The output stream is not a TTY.")
else:
    print("The output stream is a TTY.")
```
So, I would rather prefer this approach, aligning behavior with e.g. https://github.com/pavdmyt/yaspin/issues/31#issuecomment-1016861612 to move further here. It must be much more convenient than requiring developer to define custom streams upfront. Plus, if yaspin is capable to find out which streams it is attached to, there is no need to rewrite older code.

2023-10-26 15:43 UTC, bpshaver commented
@pavdmyt I do not understand how this is more convenient. The idea of detecting whether the target stream is a TTY and changing behavior or issuing a warning is a good one. But whether that stream is _always_ stdout or whether it should be configurable by the user is a separate question. 

If anything, https://github.com/pavdmyt/yaspin/issues/31#issuecomment-1016861612 supports making `sys.stderr` the default stream, _not_ `sys.stdout`. I am suggesting a less drastic change, which is simply that `yaspin` open up the possibility for a user to send the spinner to stderr. And I disagree with your comment:

> It must be much more convenient than requiring developer to define custom streams upfront.

In fact, my proposed change keeps `sys.stdout` as the default value (when `stream` is `None`)  so it does not require anything from a developer who wants to continue using `yaspin` as before. The change is completely backwards compatible. And there is no need to define custom streams. stdout or stderr should both be compatible streams and neither are "custom."

2023-10-30 16:01 UTC, pavdmyt commented
I think, I need to elaborate a bit more about my point. The idea behind capability to automatically detect streams to which yaspin is attached to allows to separate:
 - _spinner's stream_ (escape and color codes, spinner frames) from the 
 - _useful text_ (`.text` attribute, `write()` and possibly `.ok()` and `.fail()` methods)

So that _spinner's stream_ is always ends up in `stderr` (backwards incompatible change) and the _useful text_ in `stdout`. This way, you can make decisions which stream ends up where by simply using redirects and the default behavior stays (visually) the same, as both `stderr` and `stdout` are attached to the TTY by default. This would allow doing `python foo.py > foo.log` (from your example above) having the _useful text_ inside `foo.log`, while _spinner's stream_ got rendered in the terminal window (as `stderr` remained attached to TTY). And this doesn't require any code changes using `stream` argument or attribute.

To summarize, we want to have _spinner's stream_ and _useful text_ clearly separated so that user can decide what to do with these streams. Having such feature, I'm not sure about the value of having an additional `stream` argument (please correct me if I'm wrong or in case I'm missing something).

2023-11-01 16:50 UTC, bpshaver commented
I understand now, thanks!

I would call the `.text`, etc. _accompanying text_. Under normal circumstances, it is right next to the spinner. You're assuming that when the output is redirected to a non-TTY stream, however, the _accompanying text_ should be interpreted as _useful text_ and go to that non-TTY stream. But I'm not so sure that assumption makes sense for all users.

In the issue I was trying to tackle ( https://github.com/mandiant/capa/issues/1812 ) the accompanying text should go to `stderr` (remaining next to the spinner graphic) while useful text going to the non-TTY stream is everything contained within the spinner context:

```bash
$ python foo.py > foo.log
⠋ Analyzing data...
```

while program output goes to `foo.log`.

I understand a sensible default may be to send accompanying text to the non-TTY stream, but this example I think illustrates a case where that is not desired.

2023-11-03 13:51 UTC, pavdmyt commented
> In the issue I was trying to tackle ( https://github.com/mandiant/capa/issues/1812 ) the accompanying text should go to stderr (remaining next to the spinner graphic) while useful text going to the non-TTY stream is everything contained within the spinner context

I'm not sure I've understood this correctly, "accompanying text should go to `stderr` while useful text going to the non-TTY stream" - isn't accompanying and useful text are the same entities? It is also possible to redirect `stderr` to the non-TTY stream.

2023-11-03 14:26 UTC, bpshaver commented
_accompanying text_ is my name for whatever text normally goes right next to the spinner. You called it _useful text_, which is begging the question with respect to where it should go in the corner cases we're discussing. Call them what you like, but I'm pointing to three different types of text (not two):

- The actual spinner - should probably never go to a non-TTY stream
- Some text to the right of the spinner (`.text`, etc.) - maybe should go to a non-TTY stream. Probably depends on the user.
- Normal text written as result of `print` calls and the like - should be redirected as normal, unaffected by being within a `yaspin` spinner context.

2024-03-28 03:22 UTC, odisseus commented on yaspin/core.py
> +    def is_jupyter(self) -> bool:
I am pretty sure that Jupyter is not the only front-end capable of intercepting the output stream.

2024-03-28 03:24 UTC, odisseus commented on yaspin/core.py
> +    # Static
What is the purpose of this comment?

2024-03-28 03:28 UTC, odisseus commented
What is the status of this pull request? How can I help getting it merged?

2024-05-29 14:11 UTC, bpshaver commented
Seems like @pavdmyt disagreed with my reasoning and the discussion ended.

2025-09-19 18:46 UTC, darkpanda0 commented
We are in the process of migrating from the [halo](https://pypi.org/project/halo/) spinner, because it is no longer actively maintained. yaspin was the obvious choice, but I'm not sure if we will be able to use it without this feature. Our spinner is shared across various components that  individual developers can take advantage of, if the control of the flow passes to their module. I have a wrapper class to minimize the code changes necessary for developers. Some of the time our app is instructed to output json. When I am redirecting to a file, I am still getting spinner messages in the json file. [halo](https://pypi.org/project/halo/) simply allows us to choose sys.stderr, so not having that option is making it look like the transition to yaspin might not work.

I'm currently testing with python 3.11.4 using yaspin 3.1.0

2025-09-19 19:25 UTC, bpshaver commented on yaspin/core.py
> +    def is_jupyter(self) -> bool:
Pretty sure that is not my code

2025-09-19 19:26 UTC, bpshaver commented
@darkpanda0 I share your concerns. I just updated my PR with the latest from upstream so that @pavdmyt can re-review. Maybe you can try my branch to see if it works for you?

Can we get this merged in? @odisseus would probably like to see it merged as well.

2025-10-05 11:27 UTC, pavdmyt commented on yaspin/core.py
> +        self._stream_lock = threading.Lock()
`self._stdout_lock` should be removed, it is not used anywhere after adding `_stream_lock`.

2025-10-05 14:59 UTC, pavdmyt requested changes
We cannot simply suppress errors and ignore test failures, needs to be fixed.

2025-10-05 14:59 UTC, pavdmyt commented on tests/test_in_out.py
> +            sp.stop()
The issue is that `capsys` closes the file handles during teardown, but the spinner is still trying to write to them.

E.g. during test teardown, `capsys` closes the `stdout` stream, but when `sp.stop()` is called, it tries to call `_clear_line()` which attempts to write to the closed stream.

2025-10-05 15:01 UTC, pavdmyt commented on yaspin/core.py
> +        return not self._stream.isatty()
`is_jupyter` was deprecated.

2025-10-05 15:03 UTC, pavdmyt commented on yaspin/core.py
>              Yaspin._warn_color_disabled()
`self._stream` call is the first thing in constructor, this is also well-tested.

2025-10-07 19:47 UTC, merged

2025-10-07 19:47 UTC, pavdmyt commented
Will include this into the next Yaspin release.

2025-10-11 08:54 UTC, pavdmyt commented
Included in [v3.3.0](https://github.com/pavdmyt/yaspin/releases/tag/v3.3.0).